config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'logout', to: 'sessions#destroy'

  get '/auth/uber', as: :login
  get "/auth/uber/callback", to: "sessions#create"

  get 'dashboard', to: 'users#show'

  resources :user_trips, only: [:create, :index]
  resources :ride_estimates, only: [:create, :index]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :estimates, only: [:index]
      resources :user_trips, only: [:create]
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Bus-or-Uber", root_path %></li>
      </ul>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Dashboard", dashboard_path %></li>
              <li><%= link_to "Estimate a Ride", ride_estimates_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "logout", logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in with Uber", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusOrUber</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href="../../../assets/stylesheets/main.css" type="html/css" >
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |type, msg| %>
      <div class="well">
        <p>
          <center style='color:blue'><%= content_tag :div, msg.html_safe %></center>
        </p>
      </div>
    <% end %>
  </div>

<%= yield %>

<%= javascript_include_tag 'application' %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>